/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : GD
 #	author : miyako
 #	2016/09/23
 #
 # --------------------------------------------------------------------------------*/



// --- Filter
void GD_Filter(sLONG_PTR *pResult, PackagePtr pParams);

// --- Animation
void GD_Animate(sLONG_PTR *pResult, PackagePtr pParams);

// --- Rotation
void GD_Rotate(sLONG_PTR *pResult, PackagePtr pParams);

#define gdLoopInfinite 0
#define CMD_CONVERT_PICTURE 1002
#define kcpRetainOnly 1

#define IMG_FILTER_NEGATE 1
#define IMG_FILTER_GRAYSCALE 2
#define IMG_FILTER_EDGEDETECT 3
#define IMG_FILTER_EMBOSS 4
#define IMG_FILTER_GAUSSIAN_BLUR 5
#define IMG_FILTER_SELECTIVE_BLUR 6
#define IMG_FILTER_MEAN_REMOVAL 7
#define IMG_FILTER_SMOOTH 8
#define IMG_FILTER_CONTRAST 9
#define IMG_FILTER_BRIGHTNESS 10
#define IMG_FILTER_SCATTER 11
#define IMG_FILTER_PIXELATE 12
#define IMG_FILTER_COLORIZE 13
